services:
  ingestion-app:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: DataLakeHandler
    env_file: .env
    volumes:
      - ./:/app
      # - ${BULK_OFFSET_FILE}:/app/last_ingest_offset.pkl
      - ${CHECKPOINT_PATH}:/tmp/delta/checkpoints
    networks:
      - datanet
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    restart: unless-stopped


networks:
  datanet:
    external: true