services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: data-automation-app
    env_file: .env
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    volumes:
      - ./:/app
      - ${HOST_DATA_DIRECTORY}:/app/data
    # depends_on:
    #   kafka:
    #     condition: service_healthy
    #   zookeeper:
    #     condition: service_healthy
    ports:
      - "8000:8000"
    command: [ "python", "main.py", "--mode", "${PROCESSING_MODE}" ]

volumes:
  pgdata:
